SET STATEMENT_TIMEOUT = 0;
SET LOCK_TIMEOUT = 0;
SET IDLE_IN_TRANSACTION_SESSION_TIMEOUT = 0;
SET CLIENT_ENCODING = 'UTF8';
SET STANDARD_CONFORMING_STRINGS = ON;
SELECT PG_CATALOG.SET_CONFIG('SEARCH_PATH', '', FALSE);
SET CHECK_FUNCTION_BODIES = FALSE;
SET XMLOPTION = CONTENT;
SET CLIENT_MIN_MESSAGES = WARNING;
SET ROW_SECURITY = OFF;

SET DEFAULT_TABLESPACE = '';

SET DEFAULT_TABLE_ACCESS_METHOD = HEAP;

CREATE TABLE PUBLIC.USERS
(
    USER_ID     SERIAL PRIMARY KEY,
    SURNAME     VARCHAR,
    NAME        VARCHAR,
    FATHERSNAME VARCHAR,
    EMAIL       VARCHAR,
    PASSWORD    VARCHAR,
    CITY        VARCHAR,
    REGION      VARCHAR,
    ENABLE      BOOLEAN,
    CREATED_AT  TIMESTAMP DEFAULT (NOW())
);

CREATE TABLE PUBLIC.FACULTIES
(
    FACULTY_ID    SERIAL PRIMARY KEY,
    TITLE         VARCHAR,
    ALL_PLACES    INT,
    BUDGET_PLACES INT
);

CREATE TABLE PUBLIC.SUBJECTS
(
    SUBJECT_ID SERIAL PRIMARY KEY,
    TITLE      VARCHAR,
    MARK       INT
);

CREATE TABLE PUBLIC.STATEMENTS
(
    STATEMENT_ID SERIAL PRIMARY KEY,
    FINALIZED    BOOLEAN,
    FACULTY_ID   INT,
    CREATED_AT   TIMESTAMP DEFAULT (NOW())
);

CREATE TABLE PUBLIC.USER_ROLE
(
    ROLE_ID SERIAL PRIMARY KEY,
    USER_ID INT
);

CREATE TABLE PUBLIC.USERS_STATEMENTS (
    STATEMENT_ID INT,
    USER_ID INT
);

CREATE TABLE PUBLIC.USERS_SUBJECT
(
    USER_ID    INT,
    SUBJECT_ID INT
);

ALTER TABLE PUBLIC.USER_ROLE
    ADD FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID);

ALTER TABLE PUBLIC.USERS_STATEMENTS
    ADD FOREIGN KEY (STATEMENT_ID) REFERENCES PUBLIC.STATEMENTS (STATEMENT_ID);

ALTER TABLE PUBLIC.USERS_STATEMENTS
    ADD FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID);

ALTER TABLE PUBLIC.USERS_SUBJECT
    ADD FOREIGN KEY (SUBJECT_ID) REFERENCES PUBLIC.SUBJECTS (SUBJECT_ID);

ALTER TABLE PUBLIC.USERS_SUBJECT
    ADD FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID);

ALTER TABLE PUBLIC.STATEMENTS
    ADD FOREIGN KEY (FACULTY_ID) REFERENCES PUBLIC.FACULTIES (FACULTY_ID);

