INSERT INTO PUBLIC.SUBJECTS(TITLE, MARK)
VALUES ('Укр.мова', '125'),
       ('Математика', '125');


INSERT INTO PUBLIC.FACULTIES(TITLE, ALL_PLACES, BUDGET_PLACES)
VALUES ('Фізико-математичний факультет', 20, 5);


INSERT INTO PUBLIC.USERS(SURNAME, NAME, FATHERSNAME, EMAIL, PASSWORD, CITY, REGION, ENABLE)
VALUES ('', '', '', 'admin@mail.com', 'admin', '', '', true);


INSERT INTO PUBLIC.FACULTY_USER_SUBJECT(FACULTY_ID, USER_ID, SUBJECT_ID)
VALUES (1, 1, 1),
       (1, 1, 2);

INSERT INTO PUBLIC.ROLES (ROLE_ID, ROLE_NAME) VALUES
('1', 'Admin'), ('2', 'Applicant');


INSERT INTO PUBLIC.STATEMENTS(FINALIZED, FACULTY_ID)
VALUES (FALSE, 1);


INSERT INTO PUBLIC.ROLES_USERS(ROLE_ID, USER_ID)
VALUES (1, 1);

INSERT INTO PUBLIC.USERS_STATEMENTS(STATEMENT_ID, USER_ID)
VALUES (1, 1);

INSERT INTO PUBLIC.FACULTIES_STATEMENTS(FACULTY_ID, STATEMENT_ID)
VALUES (1, 1);